image: node:lts

before_script:  
  - apt-get update -qq && apt-get install
  - apt install -y rsync
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - cat "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
#  - deploy


build dev:
  stage: build
  only:
    - merge_request
    - dev
  script:
    - yarn
    - echo "export const BOHDISYS_API_URL = 'https://api.dev.bodhisys.io';" > env.js
    - echo "export const BOHDISYS_BASE_URL = 'https://api.dev.bodhisys.io';" >> env.js
    - echo "export const STRIPE_PUBLIC_KEY = 'pk_live_xbuOrv8Cb4oXWPns8yJvOVnL00VroSgXDR';" >> env.js
    - echo "export const STRIPE_PUBLIC_KEY_STAND = 'pk_live_xbuOrv8Cb4oXWPns8yJvOVnL00VroSgXDR';" >> env.js
    - export NODE_OPTIONS=--openssl-legacy-provider 
    - npx expo export:web

build staging:
  stage: build
  only:
    - merge_request
    - staging
  script:
    - yarn
    - echo "export const BOHDISYS_API_URL = 'https://api.staging.bodhisys.io';" > env.js
    - echo "export const BOHDISYS_BASE_URL = 'https://api.staging.bodhisys.io';" >> env.js
    - echo "export const STRIPE_PUBLIC_KEY = 'pk_live_xbuOrv8Cb4oXWPns8yJvOVnL00VroSgXDR';" >> env.js
    - echo "export const STRIPE_PUBLIC_KEY_STAND = 'pk_live_xbuOrv8Cb4oXWPns8yJvOVnL00VroSgXDR';" >> env.js
    - export NODE_OPTIONS=--openssl-legacy-provider 
    - npx expo export:web


build main:
  stage: build
  only:
    - merge_request
    - main
  script:
    - yarn
    - echo "export const BOHDISYS_API_URL = 'https://api.bodhisys.io';" > env.js
    - echo "export const BOHDISYS_BASE_URL = 'https://api.bodhisys.io';" >> env.js
    - echo "export const STRIPE_PUBLIC_KEY = 'pk_live_xbuOrv8Cb4oXWPns8yJvOVnL00VroSgXDR';" >> env.js
    - echo "export const STRIPE_PUBLIC_KEY_STAND = 'pk_live_xbuOrv8Cb4oXWPns8yJvOVnL00VroSgXDR';" >> env.js
    - export NODE_OPTIONS=--openssl-legacy-provider 
    - npx expo export:web
